#!/bin/bash

# declare a name for this job to be sample_job
#PBS -N shared_mem_dengo-baseline

####  #PBS -k o
##### #PBS -j oe
#PBS -o __baseline_noscale_nodge_rejac.out
#PBS -e baseline_scale_nodge.err
# request 1 node
#PBS -l nodes=1:ppn=1:gpus=1
# request 4 hours and 30 minutes of cpu time
#PBS -l walltime=00:10:00
# mail is sent to you when the job starts and when it terminates or aborts
#PBS -m bea
# specify your email address
#### #PBS -M kwoksun2@illinois.edu
# By default, PBS scripts execute in your home directory, not the
# directory from which they were submitted. The following line
# places you in the directory from which the job was submitted.
cd $PBS_O_WORKDIR
make clean
make test
# run memcheck

# cuda-memcheck ./test 8192 1.0e10 3000.0 1.0e-4


./test 8192 1.0e0 3000.0 1.0e-4
./test 8192 1.0e1 3000.0 1.0e-4
./test 8192 1.0e2 3000.0 1.0e-4
./test 8192 1.0e3 3000.0 1.0e-4
./test 8192 1.0e4 3000.0 1.0e-4
./test 8192 1.0e5 3000.0 1.0e-4
./test 8192 1.0e6 3000.0 1.0e-4
./test 8192 1.0e7 3000.0 1.0e-4
./test 8192 1.0e8 3000.0 1.0e-4
./test 8192 1.0e9 3000.0 1.0e-4
./test 8192 1.0e10 3000.0 1.0e-4
./test 8192 1.0e11 3000.0 1.0e-4
./test 8192 1.0e12 3000.0 1.0e-4
./test 8192 1.0e13 3000.0 1.0e-4
./test 8192 1.0e14 3000.0 1.0e-4


# run the program
#for i in {1..10}
#do
#	./test 8192 1.0e12 3000.0 1.0e-4
#done
# cuda-memcheck ./interp_rates
