#!/bin/bash

make clean
make OPTIONS="-DMAX_NCELLS=1" 

rm -rf cvdls_solution
mkdir cvdls_solution

for i in {1..256}
do
    echo "$i th strip" 
    time ./run_dengo input_data/"$i.h5" cvdls_solution/"$i""_solution.h5"
    python -W ignore test_accuracy.py -t cvdls_solution/"$i""_solution.h5" -s accurate_solution/"$i"_accurate_solution.h5 
done
