#!/bin/bash

make clean
make OPTIONS="-DCVSPILS -DMAX_NCELLS=1024"

rm -rf cvspils_solution
mkdir cvspils_solution

for i in {1..2}
do
    echo "$i th strip" 
    time ./run_dengo input_data/"$i.h5" cvspils_solution/"$i""_solution.h5"
    python -W ignore test_accuracy.py -t cvspils_solution/"$i""_solution.h5" -s accurate_solution/"$i"_accurate_solution.h5 
done
