#!/bin/bash 

# declare a name for this job to be sample_job
#PBS -N shared_performance 

#PBS -k o
#PBS -j oe

# request 1 node
#PBS -l nodes=1:ppn=1:gpus=1
# request 4 hours and 30 minutes of cpu time
#PBS -l walltime=12:00:00        
# mail is sent to you when the job starts and when it terminates or aborts
#PBS -m bea
# specify your email address
#PBS -M kwoksun2@illinois.edu
# By default, PBS scripts execute in your home directory, not the 
# directory from which they were submitted. The following line 
# places you in the directory from which the job was submitted.  
cd $PBS_O_WORKDIR
make clean
make test
# run the program

./run_test_timeout.py

#./test 8192 1.0e4 1000.0 1.0e-6 
#./test 16384 1.0e4 1000.0 1.0e-6 
#./test 32768 1.0e4 1000.0 1.0e-6 
#./test 262144 1.0e4 1000.0 1.0e-6 



#nvprof -f -o shared_timeline.prof ./test 
#nvprof --kernels "intDriver" --analysis-metrics -f -o shared_analysis.prof ./test 
#cuda-memcheck ./test

#cuda-memcheck ./test./test
# cuda-memcheck ./interp_rates
