name: deploy-book

on: [push]

jobs:
  deploy-book:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
            auto-update-conda: true
            auto-activate-base: true
            python-version: ${{matrix.python-version}}
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          conda install -c conda-forge "sundials>=6.2"
          conda install ChiantiPy Cython h5py Jinja2 numpy setuptools sympy matplotlib pytest unyt pip jupyter-book -c conda-forge
          pip install -e .
          sudo apt-get update
          sudo apt-get install -y libtool libtool-bin build-essential

      - name: Build the Book
        run: |
          cd cookbook
          jupyter-book build .

      # Push the book's HTML to github-pages
      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v3.6.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN  }}
          publish_dir: ./_build/html
