name: Dengo Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
            auto-update-conda: true
            auto-activate-base: true
            python-version: ${{matrix.python-version}}
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
          conda install -c conda-forge sundials>=6.2.0
      - name: Setting Environment Variables
        env:
          HDF5_PATH: "$CONDA"
          SUITESPARSE_PATH: "$CONDA"
          CVODE_PATH: "$CONDA"
          DENGO_INSTALL_PATH: "$GITHUB_WORKSPACE/dengo_install"
        run: |
          pytest -v -x
