name: Dengo Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
            auto-update-conda: true
            auto-activate-base: true
            python-version: ${{matrix.python-version}}
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -e .
          conda install -c conda-forge sundials
      - name: Check Sundials Path
        run: |
          ls $CONDA/lib/libsundials_*
      - name: Setting Environment Variables
        env:
          HDF5_PATH: $CONDA
          SUITESPARSE_PATH: $CONDA
          
      - name: Test with pytest
        run: |
          pytest -v -x
