name: Dengo Testing

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9"]

    steps:
      - name: Setup Miniconda
        uses: conda-incubator/setup-miniconda@v2.1.1
        with:
            auto-update-conda: true
            auto-activate-base: true
            python-version: ${{matrix.python-version}}
      - uses: actions/checkout@v3
      - name: Install dependencies
        run: |
          conda install ChiantiPy Cython h5py Jinja2 numpy setuptools sympy matplotlib pytest unyt sundials>=6.2.0
          pip install -e .
      - name: Setting Environment Variables
        run: |
          export HDF5_PATH=${CONDA}
          export SUITESPARSE_PATH=${CONDA}
          export CVODE_PATH=${CONDA}
          export DENGO_INSTALL_PATH=${{github.workspace}}/dengo_install

          echo "$HDF5_PATH"
          echo "$DENGO_INSTALL_PATH"
          pytest -v -x
